version: "3.9"

services:
    app:
        container_name: php-apache-setup
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}            
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        ports:
            - 85:80             
        depends_on:
            - redis
        networks:
            - setup            
    db:
        image: mysql:8
        container_name: mysql-setup
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: dbsetup
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: teste
        volumes:
            - mysql_data_setup:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password            
        networks:
            - setup
    phpmyadmin:
        image: phpmyadmin:5
        container_name: phpmyadmin-setup
        ports:
            - 8086:80
        restart: "no"
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - setup   
    redis:
        image: redis:7
        container_name: redis-setup
        volumes:
            - redis_data_setup:/data        
        networks:
            - setup

networks:
    setup:

volumes:
    mysql_data_setup:
        driver: local       
    redis_data_setup:
        driver: local
