version: "3.9"

services:
    app:
        container_name: php-apache-etc
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}            
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        ports:
            - 3000:80             
        depends_on:
            - redis
        networks:
            - etc
            
    db:
        image: mysql:8
        container_name: mysql-etc
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: dbmodelo
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: etc
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        command: --default-authentication-plugin=mysql_native_password            
        networks:
            - etc

    phpmyadmin:
        image: phpmyadmin:5
        container_name: phpmyadmin-etc
        ports:
            - 8082:80
        restart: "no"
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - etc   

    redis:
        image: redis:latest
        container_name: redis-etc
        networks:
            - etc

networks:
    etc:
        driver: bridge